# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME = "givelog-plus"
FQDN = "givelog-plus.local"
IP_ADDRESS = "192.168.99.99"

# DB設定
DB_USER = "givelog_plus_user"
DB_PASS = "givelog_plus_pass"
DB_NAME = "givelog_plus_development"
TEST_DB_NAME = "givelog_plus_test"

# synced_folder設定
SOURCE = "../src"
TARGET = "/srv/httpd/"


Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  if Vagrant.has_plugin?("vagrant-hostsupdater")
    config.hostsupdater.aliases = [
      FQDN,
      "salon-dealer.local"
    ]
  end

  config.vm.synced_folder SOURCE, TARGET, \
          create: true, owner: 'vagrant', group: 'vagrant', \
          mount_options: ['dmode=777,fmode=776']

  if defined? IP_ADDRESS
    config.vm.network :private_network, ip: IP_ADDRESS
    config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  end

  if defined? HOSTNAME
    config.vm.hostname = HOSTNAME
  end

  config.vm.provider :virtualbox do |vb|
    if defined? HOSTNAME
      vb.name = HOSTNAME
    end
    # vb.gui = true
    # vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "shell" do |s|
    s.path = "scripts/common.sh"
  end

#  config.vm.provision "shell" do |s|
#    s.path = "scripts/mailcatcher.sh"
#  end

  config.vm.provision "shell" do |s|
    s.name = "setup mysql database and user"
    s.env = {
      :DB_NAME => DB_NAME,
      :TEST_DB_NAME => TEST_DB_NAME,
      :DB_USER => DB_USER,
      :DB_PASS => DB_PASS,
    }
    s.path = "scripts/mysql.sh"
  end

  config.vm.provision "shell" do |s|
    s.path = "scripts/php.sh"
  end

  config.vm.provision "shell" do |s|
    s.name = "setup composer"
    s.path = "scripts/php_composer.sh"
  end

  config.vm.provision :shell, :inline => <<-EOT
    cp -f /vagrant/etc/dev.conf /etc/httpd/conf.d/
    cp -f /vagrant/etc/httpd-php.conf /etc/httpd/conf.d/

    conf=/etc/httpd/conf.d/dev.conf

    if [[ -n #{FQDN} ]]; then
      sed -i -e "s@#ServerName DUMMY@ServerName #{FQDN}@" ${conf}
    fi

    systemctl restart httpd.service

    export CAKE_ENV="development"; /srv/httpd/givelog-plus/bin/cake migrations migrate
    export CAKE_ENV="development"; /srv/httpd/givelog-plus/bin/cake migrations seed

  EOT

  config.vm.provision "shell", inline: <<-SHELL
    yum clean all
  SHELL
end
